<?php

namespace Database\Factories;

use App\Models\Notification;
use Illuminate\Database\Eloquent\Factories\Factory;
use Joy\VoyagerExport\Notifications\Export;
use Joy\VoyagerImport\Notifications\Import;
use stdClass;
use TCG\Voyager\Facades\Voyager;

class NotificationFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Notification::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        $notificationType = $this->faker->randomKey([
            Export::class => 'Export',
            Import::class => 'Import',
            // ResetPassword::class => 'ResetPassword',
            // VerifyEmail::class => 'VerifyEmail',
        ]);

        $notifiableType = $this->faker->randomKey([
            // '' => 'None',
            Voyager::modelClass('Account') => 'Account',
            Voyager::modelClass('AccountsAudit') => 'AccountsAudit',
            Voyager::modelClass('AccountsBug') => 'AccountsBug',
            Voyager::modelClass('AccountsCase') => 'AccountsCase',
            Voyager::modelClass('AccountsContact') => 'AccountsContact',
            Voyager::modelClass('AccountsCstm') => 'AccountsCstm',
            Voyager::modelClass('AccountsOpportunity') => 'AccountsOpportunity',
            Voyager::modelClass('AclAction') => 'AclAction',
            Voyager::modelClass('AclRole') => 'AclRole',
            Voyager::modelClass('AclRolesAction') => 'AclRolesAction',
            Voyager::modelClass('AclRolesUser') => 'AclRolesUser',
            Voyager::modelClass('AddressBook') => 'AddressBook',
            Voyager::modelClass('Alert') => 'Alert',
            Voyager::modelClass('AmProjecttemplate') => 'AmProjecttemplate',
            Voyager::modelClass('AmProjecttemplatesAudit') => 'AmProjecttemplatesAudit',
            Voyager::modelClass('AmProjecttemplatesContacts1C') => 'AmProjecttemplatesContacts1C',
            Voyager::modelClass('AmProjecttemplatesProject1C') => 'AmProjecttemplatesProject1C',
            Voyager::modelClass('AmProjecttemplatesUsers1C') => 'AmProjecttemplatesUsers1C',
            Voyager::modelClass('AmTasktemplate') => 'AmTasktemplate',
            Voyager::modelClass('AmTasktemplatesAmProjecttemplatesC') => 'AmTasktemplatesAmProjecttemplatesC',
            Voyager::modelClass('AmTasktemplatesAudit') => 'AmTasktemplatesAudit',
            Voyager::modelClass('AobhBusinesshour') => 'AobhBusinesshour',
            Voyager::modelClass('AodIndex') => 'AodIndex',
            Voyager::modelClass('AodIndexAudit') => 'AodIndexAudit',
            Voyager::modelClass('AodIndexevent') => 'AodIndexevent',
            Voyager::modelClass('AodIndexeventAudit') => 'AodIndexeventAudit',
            Voyager::modelClass('AokKnowledgebase') => 'AokKnowledgebase',
            Voyager::modelClass('AokKnowledgebaseAudit') => 'AokKnowledgebaseAudit',
            Voyager::modelClass('AokKnowledgeBaseCategoriesAudit') => 'AokKnowledgeBaseCategoriesAudit',
            Voyager::modelClass('AokKnowledgebaseBaseCategory') => 'AokKnowledgebaseBaseCategory',
            Voyager::modelClass('AokKnowledgebaseCategory') => 'AokKnowledgebaseCategory',
            Voyager::modelClass('AopCaseEvent') => 'AopCaseEvent',
            Voyager::modelClass('AopCaseEventsAudit') => 'AopCaseEventsAudit',
            Voyager::modelClass('AopCaseUpdate') => 'AopCaseUpdate',
            Voyager::modelClass('AopCaseUpdatesAudit') => 'AopCaseUpdatesAudit',
            Voyager::modelClass('AorChart') => 'AorChart',
            Voyager::modelClass('AorCondition') => 'AorCondition',
            Voyager::modelClass('AorField') => 'AorField',
            Voyager::modelClass('AorReport') => 'AorReport',
            Voyager::modelClass('AorReportsAudit') => 'AorReportsAudit',
            Voyager::modelClass('AorScheduledReport') => 'AorScheduledReport',
            Voyager::modelClass('AosContract') => 'AosContract',
            Voyager::modelClass('AosContractsAudit') => 'AosContractsAudit',
            Voyager::modelClass('AosContractsDocument') => 'AosContractsDocument',
            Voyager::modelClass('AosInvoice') => 'AosInvoice',
            Voyager::modelClass('AosInvoicesAudit') => 'AosInvoicesAudit',
            Voyager::modelClass('AosLineItemGroup') => 'AosLineItemGroup',
            Voyager::modelClass('AosLineItemGroupsAudit') => 'AosLineItemGroupsAudit',
            Voyager::modelClass('AosPdfTemplate') => 'AosPdfTemplate',
            Voyager::modelClass('AosPdfTemplatesAudit') => 'AosPdfTemplatesAudit',
            Voyager::modelClass('AosProduct') => 'AosProduct',
            Voyager::modelClass('AosProductCategoriesAudit') => 'AosProductCategoriesAudit',
            Voyager::modelClass('AosProductCategory') => 'AosProductCategory',
            Voyager::modelClass('AosProductsAudit') => 'AosProductsAudit',
            Voyager::modelClass('AosProductsQuote') => 'AosProductsQuote',
            Voyager::modelClass('AosProductsQuotesAudit') => 'AosProductsQuotesAudit',
            Voyager::modelClass('AosQuote') => 'AosQuote',
            Voyager::modelClass('AosQuotesAosInvoicesC') => 'AosQuotesAosInvoicesC',
            Voyager::modelClass('AosQuotesAudit') => 'AosQuotesAudit',
            Voyager::modelClass('AosQuotesOsContractsC') => 'AosQuotesOsContractsC',
            Voyager::modelClass('AosQuotesProjectC') => 'AosQuotesProjectC',
            Voyager::modelClass('AowAction') => 'AowAction',
            Voyager::modelClass('AowCondition') => 'AowCondition',
            Voyager::modelClass('AowProcessed') => 'AowProcessed',
            Voyager::modelClass('AowProcessedAowAction') => 'AowProcessedAowAction',
            Voyager::modelClass('AowWorkflow') => 'AowWorkflow',
            Voyager::modelClass('AowWorkflowAudit') => 'AowWorkflowAudit',
            Voyager::modelClass('Bug') => 'Bug',
            Voyager::modelClass('BugsAudit') => 'BugsAudit',
            Voyager::modelClass('Call') => 'Call',
            Voyager::modelClass('CallsContact') => 'CallsContact',
            Voyager::modelClass('CallsLead') => 'CallsLead',
            Voyager::modelClass('CallsReschedule') => 'CallsReschedule',
            Voyager::modelClass('CallsRescheduleAudit') => 'CallsRescheduleAudit',
            Voyager::modelClass('CallsUser') => 'CallsUser',
            Voyager::modelClass('Campaign') => 'Campaign',
            Voyager::modelClass('CampaignLog') => 'CampaignLog',
            Voyager::modelClass('CampaignsAudit') => 'CampaignsAudit',
            Voyager::modelClass('CampaignTrkr') => 'CampaignTrkr',
            Voyager::modelClass('CrmCase') => 'CrmCase',
            Voyager::modelClass('CasesAudit') => 'CasesAudit',
            Voyager::modelClass('CasesBug') => 'CasesBug',
            Voyager::modelClass('CasesCstm') => 'CasesCstm',
            Voyager::modelClass('Config') => 'Config',
            Voyager::modelClass('Contact') => 'Contact',
            Voyager::modelClass('ContactsAudit') => 'ContactsAudit',
            Voyager::modelClass('ContactsBug') => 'ContactsBug',
            Voyager::modelClass('ContactsCase') => 'ContactsCase',
            Voyager::modelClass('ContactsCstm') => 'ContactsCstm',
            Voyager::modelClass('ContactsUser') => 'ContactsUser',
            Voyager::modelClass('CronRemoveDocument') => 'CronRemoveDocument',
            Voyager::modelClass('Currency') => 'Currency',
            Voyager::modelClass('CustomField') => 'CustomField',
            Voyager::modelClass('Document') => 'Document',
            Voyager::modelClass('DocumentRevision') => 'DocumentRevision',
            Voyager::modelClass('DocumentsAccount') => 'DocumentsAccount',
            Voyager::modelClass('DocumentsBug') => 'DocumentsBug',
            Voyager::modelClass('DocumentsCase') => 'DocumentsCase',
            Voyager::modelClass('DocumentsContact') => 'DocumentsContact',
            Voyager::modelClass('DocumentsOpportunity') => 'DocumentsOpportunity',
            Voyager::modelClass('Eapm') => 'Eapm',
            Voyager::modelClass('Email') => 'Email',
            Voyager::modelClass('EmailAddrBeanRel') => 'EmailAddrBeanRel',
            Voyager::modelClass('EmailAddress') => 'EmailAddress',
            Voyager::modelClass('EmailAddressesAudit') => 'EmailAddressesAudit',
            Voyager::modelClass('EmailCache') => 'EmailCache',
            Voyager::modelClass('Emailman') => 'Emailman',
            Voyager::modelClass('EmailMarketing') => 'EmailMarketing',
            Voyager::modelClass('EmailMarketingProspectList') => 'EmailMarketingProspectList',
            Voyager::modelClass('EmailsBean') => 'EmailsBean',
            Voyager::modelClass('EmailsEmailAddrRel') => 'EmailsEmailAddrRel',
            Voyager::modelClass('EmailsText') => 'EmailsText',
            Voyager::modelClass('EmailTemplate') => 'EmailTemplate',
            Voyager::modelClass('Favorite') => 'Favorite',
            Voyager::modelClass('FieldsMetaDatum') => 'FieldsMetaDatum',
            Voyager::modelClass('Folder') => 'Folder',
            Voyager::modelClass('FoldersRel') => 'FoldersRel',
            Voyager::modelClass('FoldersSubscription') => 'FoldersSubscription',
            Voyager::modelClass('FpEvent') => 'FpEvent',
            Voyager::modelClass('FpEventLocation') => 'FpEventLocation',
            Voyager::modelClass('FpEventLocationsAudit') => 'FpEventLocationsAudit',
            Voyager::modelClass('FpEventLocationsFpEvents1C') => 'FpEventLocationsFpEvents1C',
            Voyager::modelClass('FpEventsAudit') => 'FpEventsAudit',
            Voyager::modelClass('FpEventsContactsC') => 'FpEventsContactsC',
            Voyager::modelClass('FpEventsFpEventDelegates1C') => 'FpEventsFpEventDelegates1C',
            Voyager::modelClass('FpEventsFpEventLocations1C') => 'FpEventsFpEventLocations1C',
            Voyager::modelClass('FpEventsLeads1C') => 'FpEventsLeads1C',
            Voyager::modelClass('FpEventsProspects1C') => 'FpEventsProspects1C',
            Voyager::modelClass('ImportMap') => 'ImportMap',
            Voyager::modelClass('InboundEmail') => 'InboundEmail',
            Voyager::modelClass('InboundEmailAutoreply') => 'InboundEmailAutoreply',
            Voyager::modelClass('InboundEmailCacheT') => 'InboundEmailCacheT',
            Voyager::modelClass('JjwgAddressCache') => 'JjwgAddressCache',
            Voyager::modelClass('JjwgAddressCacheAudit') => 'JjwgAddressCacheAudit',
            Voyager::modelClass('JjwgArea') => 'JjwgArea',
            Voyager::modelClass('JjwgAreasAudit') => 'JjwgAreasAudit',
            Voyager::modelClass('JjwgMap') => 'JjwgMap',
            Voyager::modelClass('JjwgMapsAudit') => 'JjwgMapsAudit',
            Voyager::modelClass('JjwgMapsJjwgAreasC') => 'JjwgMapsJjwgAreasC',
            Voyager::modelClass('JjwgMapsJjwgMarkersC') => 'JjwgMapsJjwgMarkersC',
            Voyager::modelClass('JjwgMarker') => 'JjwgMarker',
            Voyager::modelClass('JjwgMarkersAudit') => 'JjwgMarkersAudit',
            Voyager::modelClass('JobQueue') => 'JobQueue',
            Voyager::modelClass('Lead') => 'Lead',
            Voyager::modelClass('LeadsAudit') => 'LeadsAudit',
            Voyager::modelClass('LeadsCstm') => 'LeadsCstm',
            Voyager::modelClass('LinkedDocument') => 'LinkedDocument',
            Voyager::modelClass('Meeting') => 'Meeting',
            Voyager::modelClass('MeetingsContact') => 'MeetingsContact',
            Voyager::modelClass('MeetingsCstm') => 'MeetingsCstm',
            Voyager::modelClass('MeetingsLead') => 'MeetingsLead',
            Voyager::modelClass('MeetingsUser') => 'MeetingsUser',
            Voyager::modelClass('Note') => 'Note',
            Voyager::modelClass('Notification') => 'Notification',
            Voyager::modelClass('Oauth2client') => 'Oauth2client',
            Voyager::modelClass('Oauth2token') => 'Oauth2token',
            Voyager::modelClass('OauthConsumer') => 'OauthConsumer',
            Voyager::modelClass('OauthNonce') => 'OauthNonce',
            Voyager::modelClass('OauthToken') => 'OauthToken',
            Voyager::modelClass('OpportunitiesAudit') => 'OpportunitiesAudit',
            Voyager::modelClass('OpportunitiesContact') => 'OpportunitiesContact',
            Voyager::modelClass('OpportunitiesCstm') => 'OpportunitiesCstm',
            Voyager::modelClass('Opportunity') => 'Opportunity',
            Voyager::modelClass('OutboundEmail') => 'OutboundEmail',
            Voyager::modelClass('OutboundEmailAudit') => 'OutboundEmailAudit',
            Voyager::modelClass('Project') => 'Project',
            Voyager::modelClass('ProjectContacts1C') => 'ProjectContacts1C',
            Voyager::modelClass('ProjectCstm') => 'ProjectCstm',
            Voyager::modelClass('ProjectsAccount') => 'ProjectsAccount',
            Voyager::modelClass('ProjectsBug') => 'ProjectsBug',
            Voyager::modelClass('ProjectsCase') => 'ProjectsCase',
            Voyager::modelClass('ProjectsContact') => 'ProjectsContact',
            Voyager::modelClass('ProjectsOpportunity') => 'ProjectsOpportunity',
            Voyager::modelClass('ProjectsProduct') => 'ProjectsProduct',
            Voyager::modelClass('ProjectTask') => 'ProjectTask',
            Voyager::modelClass('ProjectTaskAudit') => 'ProjectTaskAudit',
            Voyager::modelClass('ProjectUsers1C') => 'ProjectUsers1C',
            Voyager::modelClass('Prospect') => 'Prospect',
            Voyager::modelClass('ProspectList') => 'ProspectList',
            Voyager::modelClass('ProspectListCampaign') => 'ProspectListCampaign',
            Voyager::modelClass('ProspectListsProspect') => 'ProspectListsProspect',
            Voyager::modelClass('ProspectsCstm') => 'ProspectsCstm',
            Voyager::modelClass('Relationship') => 'Relationship',
            Voyager::modelClass('Release') => 'Release',
            Voyager::modelClass('Reminder') => 'Reminder',
            Voyager::modelClass('RemindersInvitee') => 'RemindersInvitee',
            // Voyager::modelClass('Role') => 'Role',
            Voyager::modelClass('RolesModule') => 'RolesModule',
            // Voyager::modelClass('RolesUser') => 'RolesUser',
            Voyager::modelClass('SavedSearch') => 'SavedSearch',
            Voyager::modelClass('Sample') => 'Sample',
            Voyager::modelClass('Scheduler') => 'Scheduler',
            Voyager::modelClass('Securitygroup') => 'Securitygroup',
            Voyager::modelClass('SecuritygroupsAclRole') => 'SecuritygroupsAclRole',
            Voyager::modelClass('SecuritygroupsAudit') => 'SecuritygroupsAudit',
            Voyager::modelClass('SecuritygroupsDefault') => 'SecuritygroupsDefault',
            Voyager::modelClass('SecuritygroupsRecord') => 'SecuritygroupsRecord',
            Voyager::modelClass('SecuritygroupsUser') => 'SecuritygroupsUser',
            Voyager::modelClass('Spot') => 'Spot',
            Voyager::modelClass('Sugarfeed') => 'Sugarfeed',
            Voyager::modelClass('Survey') => 'Survey',
            Voyager::modelClass('Surveyquestion') => 'Surveyquestion',
            Voyager::modelClass('Surveyquestionoption') => 'Surveyquestionoption',
            Voyager::modelClass('SurveyquestionoptionsAudit') => 'SurveyquestionoptionsAudit',
            Voyager::modelClass('SurveyquestionoptionsSurveyquestionresponse') => 'SurveyquestionoptionsSurveyquestionresponse',
            Voyager::modelClass('Surveyquestionresponse') => 'Surveyquestionresponse',
            Voyager::modelClass('SurveyquestionresponsesAudit') => 'SurveyquestionresponsesAudit',
            Voyager::modelClass('SurveyquestionsAudit') => 'SurveyquestionsAudit',
            Voyager::modelClass('Surveyresponse') => 'Surveyresponse',
            Voyager::modelClass('SurveyresponsesAudit') => 'SurveyresponsesAudit',
            Voyager::modelClass('SurveysAudit') => 'SurveysAudit',
            Voyager::modelClass('Task') => 'Task',
            Voyager::modelClass('Templatesectionline') => 'Templatesectionline',
            Voyager::modelClass('Tracker') => 'Tracker',
            Voyager::modelClass('UpgradeHistory') => 'UpgradeHistory',
            Voyager::modelClass('User') => 'User',
            Voyager::modelClass('UserPreference') => 'UserPreference',
            Voyager::modelClass('UsersFeed') => 'UsersFeed',
            Voyager::modelClass('UsersLastImport') => 'UsersLastImport',
            Voyager::modelClass('UsersPasswordLink') => 'UsersPasswordLink',
            Voyager::modelClass('UsersSignature') => 'UsersSignature',
            Voyager::modelClass('Vcal') => 'Vcal',
        ]);

        return [
            'type'               => $notificationType,
            'notifiable_type'    => $notifiableType,
            'notifiable_id'      => (new $notifiableType)->factory(),
            'data'               => new \stdClass(),
            'parent_id'          => null,
            'status'             => $this->faker->randomKey([
                'ACTIVE' => 'ACTIVE',
                'INACTIVE' => 'INACTIVE',
                'EXPIRED' => 'EXPIRED',
            ]),
            'read_at' => $this->faker->dateTimeBetween('-1month', 'now'),
            'created_at'      => $this->faker->dateTime(),
            'updated_at'      => $this->faker->dateTime(),
            // 'deleted_at' => $this->faker->dateTime(),
        ];
    }

    /**
     * Indicate that the model's read status should be unread.
     *
     * @return static
     */
    public function unread()
    {
        return $this->state(fn (array $attributes) => [
            'read_at' => null,
        ]);
    }
}
